spring:
  application:
    name: sb-ref-test

server:
  port: 28081

management:
  info:
    build:
      enabled: true
    git:
      enabled: true
  endpoint:
    info:
      enabled: true
    health:
      show-details: always
    mappings:
      enabled: true
  server:
    port: 28082
  endpoints:
    web:
      base-path: /mgmt
      exposure:
        include: health,info,env,mappings,prometheus

logging:
  pattern:
    console: "%date - %logger{30} - %message%n"
  level:
    org.springframework: WARN

