spring:
  application:
    name: sb-ref-test

server:
  port: 28081

management:
  info:
    build:
      enabled: true
    git:
      enabled: true
  endpoint:
    info:
      enabled: true
    health:
      show-details: always
    mappings:
      enabled: true
    metrics:
      enabled: true
  server:
    port: 28082
  endpoints:
    web:
      base-path: /mgmt
      exposure:
        include: health,info,env,mappings,metrics,prometheus
  metrics:
    tags:
      host: ${HOST_NAME}
      environment: dev
  tracing:
    sampling:
      probability: 1.0
    enabled: true
    propagation:
      type: b3
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    console: "%date %5p [%X{traceId},%X{spanId}] %logger{30} - %message%n"
  level:
    org.springframework: WARN

custom:
  weather:
    url: https://local.weather.com
    port: 8081
    max-retries: 3
    timeout: 60
    token: x3ddf22
